name: Build and Publish to Github Container Registry 

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish image
        run: |
          docker login --username maldorne-bot --password ${{ secrets.MALDORNE_BOT_GHCR_TOKEN }} ghcr.io
          docker build --no-cache . -t ghcr.io/maldorne/mudos:v21.7
          docker push ghcr.io/maldorne/mudos:v21.7
